version: "3.7"
services:
  cortex:
    container_name: cortex
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    environment:
      - 'JOB_DIRECTORY=/opt/cortex/jobs'
    ports:
      - '0.0.0.0:9001:9001'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true

  thehive:
    container_name: thehive
    image: 'strangebee/thehive:5.2'
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - cortex
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
  cassandra:
    image: 'cassandra:4'
    mem_limit: 1600m
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=1024M
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    mem_limit: 1500m
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:
